// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vctxvlkzoyqrwnletgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdHh2bGt6b3lxcndubGV0Z3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQ4NDMsImV4cCI6MjA2ODgzMDg0M30.ljyLcxUiUZ0eXo9qBjbWTvYu0h8HViOGEkqfsGoQJxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const STORAGE_KEY = 'express-credit-auth-v1';
const LEGACY_STORAGE_KEYS = [`sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`];

const migrateLegacyAuthStorage = () => {
  if (typeof window === 'undefined') return;
  try {
    if (!window.localStorage.getItem(STORAGE_KEY)) {
      const legacyKey = LEGACY_STORAGE_KEYS.find((key) => window.localStorage.getItem(key));
      if (legacyKey) window.localStorage.setItem(STORAGE_KEY, window.localStorage.getItem(legacyKey)!);
    }
  } catch (error) {
    console.warn('[auth] Unable to migrate legacy auth storage:', error);
  }
};

migrateLegacyAuthStorage();

// Single, stock browser client. The Supabase SDK already dedupes refresh calls
// via its internal lock; the previous custom guardedFetch was returning synthetic
// 200s with the old expires_at, which made the SDK reschedule a refresh immediately
// — that produced the refresh-token storm seen in auth logs (50+ refreshes in 5s,
// ending in 429). Stock config restores normal behavior.
const createSupabaseBrowserClient = () => createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

declare global {
  interface Window {
    __EXPRESS_CREDIT_SUPABASE__?: ReturnType<typeof createSupabaseBrowserClient>;
  }
}

export const supabase = typeof window !== 'undefined'
  ? (window.__EXPRESS_CREDIT_SUPABASE__ ??= createSupabaseBrowserClient())
  : createSupabaseBrowserClient();