// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vctxvlkzoyqrwnletgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdHh2bGt6b3lxcndubGV0Z3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQ4NDMsImV4cCI6MjA2ODgzMDg0M30.ljyLcxUiUZ0eXo9qBjbWTvYu0h8HViOGEkqfsGoQJxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const STORAGE_KEY = 'express-credit-auth-v1';

const createSupabaseBrowserClient = () => createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    lock: async (_name, _acquireTimeout, fn) => await fn(),
  }
});

declare global {
  interface Window {
    __EXPRESS_CREDIT_SUPABASE__?: ReturnType<typeof createSupabaseBrowserClient>;
  }
}

export const supabase = typeof window !== 'undefined'
  ? (window.__EXPRESS_CREDIT_SUPABASE__ ??= createSupabaseBrowserClient())
  : createSupabaseBrowserClient();